package br.com.tinnova.veiculo.domain;

public enum Marca {
VOLVO, VOLKSWAGEN, TROLLER, TOYOTA, TAC, SUZUKI, SUBARU, SSANGYONG, 
SMART, SHINERAY, SEAT, ROLLS_ROYCE, RENAULT, RELY, RAM, PORSCHE, PEUGEOT,
NISSAN, MORRIS_GARAGES,MITSUBISHI, MINI, MERCEDES_BENZ,MCLAREN,AUDI, BMW,
CHEVROLET, CITROEN, CROSS_LANDER, DODGE, FERRARI, FIAT, FORD, HONDA,
HYUNDAI, IVECO, JAC, JEEP, KIA, LAMBORGHINI, LAND_ROVER;
}